os:             linux
dist:           xenial

language: go

go:
- "1.14"
- master

jobs:
  include:

  - &build-stage
    stage: build
    env: GOOS=linux GOARCH=amd64
    install: true
    script: go run main.go

  - &test-stage
    stage: test
    script: go test ./... -v -cover